### ISSUE TITLE
support of debian 11

### ISSUE THREAD

**Issue by VincentGuyader** [rstudio/r-builds#114]
dear RStudio,

 do you have visibility on debian 11 support? for R binaries? (R itself, not Rpackages)

Regards

**Comment by VincentGuyader** [comment]
thanks !

Regards

**Comment by glin** [comment]
R binaries should now be available for Debian 11. The website hasn't been updated yet, but you download the binaries using `/debian-11/` URLs, like: https://cdn.rstudio.com/r/debian-11/pkgs/r-4.1.3_1_amd64.deb

**Comment by VincentGuyader** [comment]
thanks a lot
