### ISSUE TITLE
Deploy r-builds job failing from permissions error

### ISSUE THREAD

**Issue by glin** [rstudio/r-builds#117]
The r-builds deploy job started failing after we added `R-next` builds and changed the CloudWatch event rule to include `next` in the daily builds (https://github.com/rstudio/r-builds/pull/116): https://build.rstudioservices.com/blue/organizations/jenkins/r-builds%2Fr-builds/detail/master/36/pipeline

See error log at: https://build.rstudioservices.com/blue/organizations/jenkins/r-builds%2Fdeploy-r-builds/detail/deploy-r-builds/89/pipeline

**Comment by jforest** [comment]
Added the required permissions to config-as-code and deployed.  This is all set
