### ISSUE TITLE
Set User Agent Header

### ISSUE THREAD

**Issue by slopp** [rstudio/r-builds#15]
Beginning in R versions > 3.6, the user agent header is no longer set by default. We should include a user agent header that specifies the R version, and potentially the distribution id; this would alleviate the need for admins and our products to get the UA header correct, see:

https://github.com/rstudio/connect/issues/14583
https://github.com/rstudio/rstudio/pull/4889
https://community.rstudio.com/t/url-encoding-or-user-agent-encoding/35532

**Comment by jeroen** [comment]
> Beginning in R versions > 3.6, the user agent header is no longer set by default. 

Is this a change in base R? I haven't noticed this. Can you point to the commit?

**Comment by slopp** [comment]
https://github.com/wch/r-source/commit/def075db88ae87104c38437a57e9327b078bb804
