### ISSUE TITLE
Quick install fails under RHEL

### ISSUE THREAD

**Issue by ricardofandrade** [rstudio/r-builds#43]
From @slopp 
> The CDN link constructed for CentOS 7 was wrong. I was using RHEL 7.2, and the R installer tried to grab the rpm from our cdn using centos-7.2 instead of centos-7 which meant that R failed to install

**Comment by glin** [comment]
This should've been fixed in https://github.com/rstudio/r-builds/pull/44, let us know if you're still running into quick install issues.
