### ISSUE TITLE
Missing libgfortran and libreadline dependencies for R 3.6.2 on CentOS 7

### ISSUE THREAD

**Issue by koverholt** [rstudio/r-builds#49]
I'm getting the following error when installing R 3.6.2 from:

```
$ curl -O https://cdn.rstudio.com/r/centos-7/pkgs/R-3.6.2-1-1.x86_64.rpm
$ sudo yum install R-3.6.2-1-1.x86_64.rpm
```

The error that I get is:

```
$ /opt/R/${R_VERSION}/bin/R --version
/opt/R/3.6.2/lib/R/bin/exec/R: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
```

I installed libgfortran manually:

```
$ sudo yum install libgfortran5
```

Then I got the following:

```
$ /opt/R/36.2/bin/R --version
-bash: /opt/R/36.2/bin/R: No such file or directory
[centos@ip-172-31-2-235 ~]$ /opt/R/3.6.2/bin/R --version
/opt/R/3.6.2/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
```

My Linux version:

```
CentOS Linux release 7.6.1810 (Core)
```

This is using the CentOS 7 AMI in the AWS Marketplace:

```
AMI ID
CentOS Linux 7 x86_64 HVM EBS ENA 1901_01-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-05713873c6794f575.4 (ami-02eac2c0129f6376b)
```

**Comment by glin** [comment]
Huh, that's odd. Could you double check the RPM you installed? `libgfortran.so.5` and `libreadline.so.7` should be dependencies of the CentOS 8 R binary, but not CentOS 7. I just tried an install of R 3.6.2 on the CentOS 7 AMI and didn't run into any issues:
```sh
$ sudo yum install -y epel-release
$ curl -O https://cdn.rstudio.com/r/centos-7/pkgs/R-3.6.2-1-1.x86_64.rpm
$ sudo yum install -y R-3.6.2-1-1.x86_64.rpm
$ /opt/R/3.6.2/bin/R --version
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

# One idea would be to double check if the rpm size and build date matches?
$ rpm -qi R-3.6.2
Name        : R-3.6.2
Version     : 1
Release     : 1
Architecture: x86_64
Install Date: Mon 06 Jan 2020 07:36:49 PM UTC
Group       : default
Size        : 102969440
License     : GPL-2
Signature   : (none)
Source RPM  : R-3.6.2-1-1.src.rpm
Build Date  : Thu 12 Dec 2019 09:08:56 AM UTC
```

If I try to use the CentOS 8 installer, I get a similar missing libgfortran/libreadline error:
```sh
$ curl -o R-3.6.2-centos8.rpm https://cdn.rstudio.com/r/centos-8/pkgs/R-3.6.2-1-1.x86_64.rpm
$ sudo yum reinstall -y R-3.6.2-centos8.rpm
$ /opt/R/3.6.2/bin/R --version
/opt/R/3.6.2/lib/R/bin/exec/R: error while loading shared libraries: libgfortran.so.5: cannot open shared object file: No such file or directory
$ ldd /opt/R/3.6.2/lib/R/lib/libR.so 
/opt/R/3.6.2/lib/R/lib/libR.so: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /opt/R/3.6.2/lib/R/lib/libR.so)
/opt/R/3.6.2/lib/R/lib/libR.so: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /opt/R/3.6.2/lib/R/lib/libR.so)
	linux-vdso.so.1 =>  (0x00007ffef9cf0000)
	libRblas.so => not found
	libgfortran.so.5 => not found
	libm.so.6 => /lib64/libm.so.6 (0x00007f0108be7000)
	libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f01089ab000)
	libreadline.so.7 => not found
```

**Comment by koverholt** [comment]
Ack, you are correct. I likely mixed the CentOS 8 installer on the CentOS 7 machine when testing on different platforms.

I just tried again on CentOS 7 with the CentOS 7 RPM and all is well. Apologies for the noise!

**Comment by glin** [comment]
No problem, glad to hear it's resolved!

**Comment by vvelizariy** [comment]
Hello.
Got same issue on AWS AMI image

`cat /proc/version 
Linux version 4.14.256-197.484.amzn2.x86_64 (mockbuild@ip-10-0-37-156) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-13) (GCC)) #1 SMP Tue Nov 30 00:17:50 UTC 2021
curl -O https://cdn.rstudio.com/r/centos-7/pkgs/R-3.6.3-1-1.x86_64.rpm
sudo yum install -y R-3.6.3-1-1.x86_64.rpm
/opt/R/3.6.3/bin/Rscript --version
R scripting front-end version 3.6.3 (2020-02-29)
/opt/R/3.6.3/bin/R --version
/opt/R/3.6.3/lib/R/bin/exec/R: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory`

Couul you please advice anything to solve issue?
