### ISSUE TITLE
Some builds hang on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by joncfoo** [rstudio/r-builds#62]
@glin and I saw some builds hang on Ubuntu 20.04 LTS during the `byte-compiling grDevices` step of the build.

From what we can tell, R <= ~3.5 is affected (3.4.3, 3.5.3 were seen hanging, while 3.6.3 and 4.0.0 seemed fine).

This has _something_ to do with including `libopenblas` as a dependency - not entirely sure why the build hangs but removing this dependency allows the builds to complete.

During the _hang_, a single CPU spins at 100%.

----
Related: https://github.com/rstudio/r-builds/pull/60
Related: https://github.com/rstudio/r-builds/pull/61

**Comment by glin** [comment]
This seems to have been a bug with the libopenblas package on Ubuntu 20.04: https://bugs.launchpad.net/ubuntu/+source/openblas/+bug/1860601
https://github.com/xianyi/OpenBLAS/issues/2642

Looks like it was fixed upstream last June, so we could try adding OpenBLAS again.

**Comment by glin** [comment]
Fixed in https://github.com/rstudio/r-builds/pull/215 (@michaelmayer2)
