### ISSUE TITLE
Get R 3.3.0, 3.3.1, 3.3.2 builds working for all distros

### ISSUE THREAD

**Issue by glin** [rstudio/r-builds#76]
R 3.3.0, 3.3.1, and 3.3.2 builds don't work for most of the newer distros, like Ubuntu 18 and CentOS 8, due to a bug in the configure script (see https://github.com/rstudio/r-builds/pull/48): https://github.com/rstudio/r-builds/blob/0eaf4ff908f5944c152f89128bbffb3f73ce1c95/handler.py#L128-L139

It has caused some pains with documentation and the quick install script (https://github.com/rstudio/r-builds/issues/36). @jimhester suggests we could just backport the patch for this bug, since the fix is pretty minor anyway: https://stat.ethz.ch/pipermail/r-devel/2017-February/073752.html

**Comment by gaborcsardi** [comment]
Closed by #179 I believe.
