### ISSUE TITLE
ModuleNotFoundError: No module named 'apt_inst'

### ISSUE THREAD

**Issue by emillykkejensen** [rstudio/r-builds#77]
Using this guide: https://docs.rstudio.com/resources/install-r/ I'm trying to install R 4.0.2 along side my current R 3.6.3.

However I persistently get this error:
```
user:~$ sudo gdebi r-${R_VERSION}_1_amd64.deb
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 38, in <module>
    from GDebi.GDebiCli import GDebiCli
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 36, in <module>
    from .DebPackage import DebPackage, DscSrcPackage
  File "/usr/share/gdebi/GDebi/DebPackage.py", line 24, in <module>
    import apt.debfile
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 23, in <module>
    import apt_inst
ModuleNotFoundError: No module named 'apt_inst'

```

What's going wrong?

**Comment by slopp** [comment]
Are you sure you are using the correct ubuntu debian? You will need to match the right debian for ubuntu version (16.04 / 18.04 / 20.04), each has its own download link on that page.

**Comment by emillykkejensen** [comment]
I am. I'm running Ubuntu 18.04 and useing https://cdn.rstudio.com/r/ubuntu-1804/pkgs/r-4.0.2_1_amd64.deb

'Solved' it by installing from scource (https://docs.rstudio.com/resources/install-r-source/)

**Comment by slopp** [comment]
Sorry for the trouble @emillykkejensen; unfortunately I was not able to reproduce this on a "fresh" ubuntu 18 ec2 instance.

**Comment by glin** [comment]
@emillykkejensen That looks like some issue with gdebi when you install new Python versions. I'm not sure how to fix it, but this might help: https://askubuntu.com/questions/1069087/modulenotfounderror-no-module-named-apt-pkg-error

Otherwise, you could try installing the package without gdebi like this:
```sh
sudo apt-get install -f -y ./r-${R_VERSION}_1_amd64.deb
```

**Comment by emillykkejensen** [comment]
It might be a Python issue - but installing from source did it.
