### ISSUE TITLE
pcre2-devel required on RHEL 7 install

### ISSUE THREAD

**Issue by Chris-Engelhardt** [rstudio/r-builds#93]
On a t2.medium EC2 instance running AMI ID ami-0916c408cb02e310b, I am attempting to follow the install steps for RHEL 7. 

On a fresh instance, I ran the following lines (from the README): 

```
sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum install yum-utils
sudo yum-config-manager --enable "rhel-*-optional-rpms"
sudo yum install wget
wget https://cdn.rstudio.com/r/centos-7/pkgs/R-4.1.0-1-1.x86_64.rpm
sudo yum install R-4.1.0-1-1.x86_64.rpm
```

However, the install process fails with the following message:

![image](https://user-images.githubusercontent.com/15039456/125326753-5df12a00-e310-11eb-8ab1-07b5089b34c5.png)

pcre2-devel does not seem to be available in the updated repos. Am I missing something obvious? 

Thanks in advance!

**Comment by glin** [comment]
Thanks for providing the AMI. You're not missing anything obvious - the RHEL 7 repositories for AWS were all renamed in December 2019 from something like `rhui-REGION-rhel-*` to `rhel-7-server-rhui-*`: https://access.redhat.com/articles/4599971. This AMI seems to have been created before the change, so the next time you run `yum update`, the RHUI repo names will all change.

You can either run `yum update` first, then trying adding the `rhel-*-optional-rpms` repo:
```sh
sudo yum update
```

Or update the RHUI client specifically to get the new repo names:
```sh
sudo yum update rh-amazon-rhui-client
```

After updating RHUI and enabling the `rhel-*-optional-rpms` repo, you can double check that the repo was added before installing R:
```sh
$ sudo yum repolist
repo id                                                         repo name                                                                                           status
epel/x86_64                                                     Extra Packages for Enterprise Linux 7 - x86_64                                                      13,621
rhel-7-server-rhui-optional-rpms/7Server/x86_64                 Red Hat Enterprise Linux 7 Server - Optional from RHUI (RPMs)   
```

If this comes up more, we could consider adding a note to the installation docs about this.

**Comment by Chris-Engelhardt** [comment]
Thank you, Greg! This was a big help!

For posterity's sake, I ran the following on a fresh EC2 and installed R without issue: 

```
sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
sudo yum update -y rh-amazon-rhui-client
sudo yum-config-manager --enable "rhel-*-optional-rpms"

export R_VERSION=4.1.0
curl -O https://cdn.rstudio.com/r/centos-7/pkgs/R-${R_VERSION}-1-1.x86_64.rpm
sudo yum install -y R-${R_VERSION}-1-1.x86_64.rpm
```

Do you have any thoughts on `yum update` vs updating the RHUI client specifically? 

The binaries for R here are outstanding! Sure beats waiting an hour to build R from source myself. Thank you all!

**Comment by glin** [comment]
@Chris-Engelhardt That's good to hear, and thanks for the feedback!

For `yum update` vs. updating the RHUI client, both will update the RHUI client in the end, so I guess it depends if you want to update all packages on your system or leave them as-is. That AMI is a few years old now, so it wouldn't be bad idea to do a `yum update` on a fresh EC2 instance.
